### ISSUE TITLE
repeating 100 and 245s

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangeindex#3]
I indexed all 140000+ sample with traject. It took about 10 minutes on my local host and 13 minutes on the dev server. 13 of the records were skipped because they had more than one title or author. For instance: http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=6308654

I can easily allow a multi-valued field for title_display or just take the first instance of a title, but aren't the 100 and 245 fields supposed to be non-repeating?

**Comment by jpstroop** [comment]
That sound about right in terms of the timing. You have an SSD on your laptop, and maybe even a faster processor.

Yes, 100 and 245 are not repeatable. These are probably coding errors and should be reported to @joycebcat . If there are that many in such a small set...yikes.

The sane thing to do, probably, is handle the error so that the record gets in, but log it (and make sure the log message includes the bib id) so that we can turn the logs over to cataloging for cleanup.

**Comment by joycebcat** [comment]
The sample record you cited has repeated fields because it is an incorrectly formatted order record for non-roman script material.  This record will be fixed at a later point when the object is received and cataloged.  1xx and 245 are not repeatable.  Please don't make allowances for them to repeat.

At this point I wouldn't worry about these records.  I'm going to check in to make sure the person isn't still creating them this way.

**Comment by tampakis** [comment]
The 13 records' bib ids:
5148991
5496031
6011153
6308654
6427173
6479597
1939828
2594156
3383693
3648184
4462238
4536536
4539189

**Comment by jpstroop** [comment]
OK. So, @tampakis, I guess just log them. Would you be able to supply the other 12 ids, just to make sure this is the only problem?

**Comment by jpstroop** [comment]
Jinx! :skull:

**Comment by jpstroop** [comment]
BTW, I'm not saying we should allow them to display or be indexed, but that maybe the records should be allowed to pass through.

On the other hand, if this record is incomplete because it's for an item we don't have yet, is there a way to know that? Presumably those shouldn't be indexed at all, or should get a special note that they're on order or something? Is there a clue in that 904? I suppose a similar issue could occur for brief records that are created for professor copies for reserves.

**Comment by joycebcat** [comment]
@tampakis @jpstroop 
Hey, one of these records is suppressed (2594156).  You need to filter these out, they shouldn't be 
appearing in our public interfaces.

I fixed the other records except for 6479597 -- I couldn't see a duplication on this record.

**Comment by jpstroop** [comment]
So, how do we know it's suppressed?

**Comment by tampakis** [comment]
@joycebcat, I redid the indexing of the sample records and turned off the setting for taking only the first instance of the 100 for author_display (non-vernacular) and it actually found over 8,000 records with repeating 100 fields. Should I send them your way?

**Comment by tampakis** [comment]
The issue for http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=6479597 appears to be that there are two 880 entries that link to 245_02, but the first one should really be linked to the 100 field as it is the author. 
2594156 appears in Voyager: http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=2594156 although you can't actually search for it.

**Comment by jpstroop** [comment]
Wonder if it's safer in general to just trust the index part (_02) rather than the whole thing. You're going to wind up having to put them in different index fields rather than the default Traject behavior anyway (for different analysis pipelines).

**Comment by joycebcat** [comment]
@tampakis @jpstroop 

There is a flag for suppressed.  Note that it applies either to the bib record (when all copies should be suppressed in the opac) or to a specific mfhd (when that mfhd should be suppressed but others should be displayed).  When I do sql I use BIB_MASTER and get the SUPPRESS_IN_OPAC flag for the bib.  I hope that helps.

Sigh.  Please send me a report of the 8000 records with the extra titles and things on them (if only staff would leave their validation on!!)

**Comment by jpstroop** [comment]
I'm not sure what "BIB_MASTER and get the SUPPRESS_IN_OPAC" means. Right now we have MARCXML records that include the holdings (maybe @tampakis can paste one in?). Eventually we'll be reliant on whatever Voyager pushes to the FTP site that is currently used by Primo. Maybe we'll get some more data then?

If that's not  going to work we may need to consider reading directly from the Oracle DB. :crying_cat_face:

**Comment by joycebcat** [comment]
I was afraid of that.  I doubt that the suppress flag gets exported into marcxml.  You will have the same issue with the flag that indicates something is on order (not yet received).

**Comment by tampakis** [comment]
Suppressed records should now be properly handled in the [bib data service](http://bibdata.princeton.edu)
